### ISSUE TITLE
Typo in About section

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/whattodo#22]
The text in the about section refers to the Where to Work tool. It should instead refer to the What To Do tool.

**Comment by Khadeeejah** [comment]
ill work on this

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much! Please let me know if you have any questions. The file that needs to be edited is https://github.com/NCC-CNC/whattodo/blob/master/inst/app/text/acknowledge-ncc.md.
