### ISSUE TITLE
Implement star-based system for inputs instead of actual numbers

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/whattodo#3]
This is to help make it easier to input data.

**Comment by jeffreyhanson** [comment]
If I remember correctly, @ricschuster and @josephrbennett and I discussed this functionality in a meeting and decided that this feature would not be desireable. This is because it would make it more difficult for users to understand how the tool works, and such a qualitative approach would introduce arbitrariness into the prioritization process. So, I'll close this issue now.

**Comment by ricschuster** [comment]
Agreed. Thanks Jeff!

**Comment by josephrbennett** [comment]
yep
