### ISSUE TITLE
acknowledgement text

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/whattodo#30]
The acknowledgement text needs to be updated to:

>The What To  Do application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University under contract with the Nature Conservancy of Canada. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

For reference the relevant file that needs to be changed is: https://github.com/NCC-CNC/whattodo/blob/master/inst/app/text/acknowledge-ncc.md

**Comment by ricschuster** [comment]
Slight modification:

>The What To Do application was developed by Jeffrey Hanson, Jaimie Vincent, and Joe Bennett at Carleton University and Richard Schuster at the Nature Conservancy of Canada. The work by Carleton University was completed under contract with the Nature Conservancy of Canada. This work was supported by generous contributions by Environment and Climate Change Canada and the Royal Bank of Canada.

**Comment by jeffreyhanson** [comment]
Ah - thanks for catching that! I mistakenly copy-pasted the wrong text from the WTW issue.

**Comment by jeffreyhanson** [comment]
If I remember correcltly, we talked about @DanWismer focussing on the WTW tool for now. So I'll address this issue now to help get the app ready for proper release.
