### ISSUE TITLE
pie charts still confusing?

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattodo#38]
I wonder if pie charts still need work? Currently, with very high budget it appears that the "solution" part of pie chart is underneath the "current" and "goal", which could make it appear like the goal is not being reached (though it is clear from output and hovering over the chart that the solution is 100% reached.

**Comment by jeffreyhanson** [comment]
Thanks for raising this! I'll take a look at this and see what I can do.

**Comment by jeffreyhanson** [comment]
Just to expand on this bug: when the user hovers the mouse over a segment of the pie chart, then a rim should appear around the pie chart to indicate the overall area encompassed by the segment. For example:

![image](https://user-images.githubusercontent.com/3610005/155901969-e25b1498-98ba-4bfa-94a1-02e421995bd3.png)

However, when the segment corresopnds to near 100%, it seems the the rim does not appear when the mouse is hovered over the segment:

![image](https://user-images.githubusercontent.com/3610005/155902020-d1ed64e2-1d22-4dc1-92d6-68946a0e2548.png)
