### ISSUE TITLE
Panels for the setting goals/weights/settings not expanding to show content

### ISSUE THREAD

**Issue by jeffreyhanson** [NCC-CNC/whattodo#51]
@jgvincent mentioned during a lab meeting that the panels for the features/themes/setting weren't working, and did not expand to show the sliders.

**Comment by jeffreyhanson** [comment]
@jgvincent, I think I've fixed the bug now - could you please take a look?

For future reference, the bug was caused because the example data on the server did not follow the conventions assumed by the app (because the server version was out of date).

**Comment by jgvincent** [comment]
It seems to be working now, thank you!

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
