### ISSUE TITLE
projects: user groups

### ISSUE THREAD

**Issue by ricschuster** [NCC-CNC/whattodo#54]
Does "What To Do" have a way to control project access/visibility similar to what we have in "Where To Work"?
I was going to upload an example from NCC, but that should not be visible to 'public'.

**Comment by jeffreyhanson** [comment]
Yeah WDT has the same project access/visibility set up to the WTW tool. So, you can set a project to be available for public, staff-beginner, staff-advanced, or admin only. To acheive this, we'll need to (i) create a YAML file for the WTD project (e.g., [similar to  this one](https://github.com/NCC-CNC/whattodo/blob/master/inst/extdata/projects/test-data/test-data.yaml) and (ii) copy the project to the server. How does that sound?

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson !

That did the trick and its working.

**Comment by jeffreyhanson** [comment]
Awesome!
